language: ruby
rvm:
- 2.2.3

install:
  - bundle install
  
# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: 
- bundle exec jekyll build
# branch whitelist, only for GitHub Pages
branches:
  only:
  - master  # test the gh-pages branch
  - lot_bug_fixes
  - lot_article_publish
  - dev_leanontree_refactoring
  - lot_design_lang_2

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  - provider: s3
    access_key_id: $AWS_SECRET_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    skip_cleanup: true
    region: us-west-2
    local-dir: _site
    detect_encoding: true
    cache_control: "max-age=60"
    on:
      branch: master
     
  - provider: s3
    access_key_id: $AWS_SECRET_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET_DEV
    skip_cleanup: true
    local-dir: _site
    detect_encoding: true
    cache_control: "max-age=60"
    on:
      branch: lot_bug_fixes

  - provider: s3
    access_key_id: $AWS_SECRET_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET_DEV
    skip_cleanup: true
    local-dir: _site
    detect_encoding: true
    cache_control: "max-age=60"
    on:
      branch: lot_article_publish

  - provider: s3
    access_key_id: $AWS_SECRET_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET_DEV
    skip_cleanup: true
    local-dir: _site
    detect_encoding: true
    cache_control: "max-age=60"
    on:
      branch: dev_leanontree_refactoring

  - provider: s3
    access_key_id: $AWS_SECRET_ID
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET_DEV
    skip_cleanup: true
    local-dir: _site
    detect_encoding: true
    cache_control: "max-age=60"
    on:
      branch: lot_design_lang_2              
