#!/usr/bin/env bash
set -e # halt script on error

SITE_DIR=_site

# Compiling SASS to CSS
sass --update assets/stylesheets:assets/stylesheets/core

cssnano assets/stylesheets/core/application.css assets/stylesheets/core/application.min.css

bundle exec jekyll build
#bundle exec htmlproof ./_site

 find $SITE_DIR \( -iname '*.html' -o -iname '*.css' -o -iname '*.js' \) -exec gzip -9 -n {} \; -exec mv {}.gz {} \;
